apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tweetnode-deployment
  labels:
    app: tweetnode
spec:
  template:
    metadata:
      labels:
        app: tweetnode
        env: prod
        tier: web
    spec:
      imagePullSecrets:
      - name: ocir-credentials
      containers:
      - name: tweetnode
        image: $PRIVATE_REGISTRY_PATH/$TENANCY_NAME/$REPO_NAME/$APP_NAME:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - containerPort: 8181
